name: 'Fortaleza CMS deployment'

on:
  pull_request:
    branches: master
    types: [closed]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cp /home/nicolas/.env.cms .env
      - run: docker compose up -d --build
      - run: docker builder prune -f
      - run: docker image prune -f
      - run: docker volume prune -f
      - run: docker network prune -f
